### ISSUE TITLE
lol i fixed it for him

### ISSUE THREAD

**Issue by ThnksCJ** [M3gaPixel/Perry-Phobos-1.9.0-Buildable-OLDLEAK#1]

**Comment by notperry12345678902** [comment]
lol these awful decomps of ancient versions is sad but funny to see

**Comment by ThnksCJ** [comment]
Lol give us an updated jar and we can update them

**Comment by M3gaPixel** [comment]
> _No description provided._

oh okay ill take down this repo

**Comment by ThnksCJ** [comment]
U don't need to I'm just saying that I've already done that and merged it with his repo
